export type Country = {
  name: string;
  iso: string;
  emoji: string;
  region: string;
};

export const FLAG_CDN = "https://flagcdn.com/w160"; // append /{iso}.png

export const COUNTRIES: Country[] = [
  { name: "Argentina", iso: "ar", emoji: "🇦🇷", region: "South America" },
  { name: "Austria", iso: "at", emoji: "🇦🇹", region: "Europe" },
  { name: "Australia", iso: "au", emoji: "🇦🇺", region: "Australia" },
  { name: "Azerbaijan", iso: "az", emoji: "🇦🇿", region: "Asia" },
  { name: "Bahrain", iso: "bh", emoji: "🇧🇭", region: "Middle East" },
  { name: "Bangladesh", iso: "bd", emoji: "🇧🇩", region: "Asia" },
  { name: "Belgium", iso: "be", emoji: "🇧🇪", region: "Europe" },
  { name: "Brazil", iso: "br", emoji: "🇧🇷", region: "South America" },
  { name: "Canada", iso: "ca", emoji: "🇨🇦", region: "North America" },
  { name: "China", iso: "cn", emoji: "🇨🇳", region: "Asia" },
  { name: "Costa Rica", iso: "cr", emoji: "🇨🇷", region: "Central America" },
  { name: "Croatia", iso: "hr", emoji: "🇭🇷", region: "Europe" },
  { name: "Cyprus", iso: "cy", emoji: "🇨🇾", region: "Europe" },
  { name: "Czech", iso: "cz", emoji: "🇨🇿", region: "Europe" },
  { name: "Denmark", iso: "dk", emoji: "🇩🇰", region: "Europe" },
  { name: "Egypt", iso: "eg", emoji: "🇪🇬", region: "Africa" },
  { name: "Estonia", iso: "ee", emoji: "🇪🇪", region: "Europe" },
  { name: "Finland", iso: "fi", emoji: "🇫🇮", region: "Europe" },
  { name: "France", iso: "fr", emoji: "🇫🇷", region: "Europe" },
  { name: "Georgia", iso: "ge", emoji: "🇬🇪", region: "Asia" },
  { name: "Germany", iso: "de", emoji: "🇩🇪", region: "Europe" },
  { name: "Ghana", iso: "gh", emoji: "🇬🇭", region: "Africa" },
  { name: "Greece", iso: "gr", emoji: "🇬🇷", region: "Europe" },
  { name: "Haiti", iso: "ht", emoji: "🇭🇹", region: "Caribbean" },
  { name: "Hungary", iso: "hu", emoji: "🇭🇺", region: "Europe" },
  { name: "Indonesia", iso: "id", emoji: "🇮🇩", region: "Asia" },
  { name: "Israel", iso: "il", emoji: "🇮🇱", region: "Asia" },
  { name: "Iran", iso: "ir", emoji: "🇮🇷", region: "Middle East" },
  { name: "Ireland", iso: "ie", emoji: "🇮🇪", region: "Europe" },
  { name: "Italy", iso: "it", emoji: "🇮🇹", region: "Europe" },
  { name: "Japan", iso: "jp", emoji: "🇯🇵", region: "Asia" },
  { name: "Kuwait", iso: "kw", emoji: "🇰🇼", region: "Middle East" },
  { name: "Luxembourg", iso: "lu", emoji: "🇱🇺", region: "Europe" },
  { name: "Madagascar", iso: "mg", emoji: "🇲🇬", region: "Africa" },
  { name: "Malaysia", iso: "my", emoji: "🇲🇾", region: "Asia" },
  { name: "Malta", iso: "mt", emoji: "🇲🇹", region: "Europe" },
  { name: "Mauritius", iso: "mu", emoji: "🇲🇺", region: "Africa" },
  { name: "Morocco", iso: "ma", emoji: "🇲🇦", region: "Africa" },
  { name: "Myanmar", iso: "mm", emoji: "🇲🇲", region: "Asia" },
  { name: "Netherlands", iso: "nl", emoji: "🇳🇱", region: "Europe" },
  { name: "New Zealand", iso: "nz", emoji: "🇳🇿", region: "Australia" },
  { name: "Norway", iso: "no", emoji: "🇳🇴", region: "Europe" },
  { name: "Oman", iso: "om", emoji: "🇴🇲", region: "Middle East" },
  { name: "Panama", iso: "pa", emoji: "🇵🇦", region: "Central America" },
  { name: "Philippines", iso: "ph", emoji: "🇵🇭", region: "Asia" },
  { name: "Poland", iso: "pl", emoji: "🇵🇱", region: "Europe" },
  { name: "Portugal", iso: "pt", emoji: "🇵🇹", region: "Europe" },
  { name: "Russia", iso: "ru", emoji: "🇷🇺", region: "Europe" },
  { name: "Saudi Arabia", iso: "sa", emoji: "🇸🇦", region: "Middle East" },
  { name: "Singapore", iso: "sg", emoji: "🇸🇬", region: "Asia" },
  { name: "Slovenia", iso: "si", emoji: "🇸🇮", region: "Europe" },
  { name: "South Africa", iso: "za", emoji: "🇿🇦", region: "Africa" },
  { name: "South Korea", iso: "kr", emoji: "🇰🇷", region: "Asia" },
  { name: "Sri Lanka", iso: "lk", emoji: "🇱🇰", region: "Asia" },
  { name: "Spain", iso: "es", emoji: "🇪🇸", region: "Europe" },
  { name: "Sweden", iso: "se", emoji: "🇸🇪", region: "Europe" },
  { name: "Switzerland", iso: "ch", emoji: "🇨🇭", region: "Europe" },
  { name: "Tanzania", iso: "tz", emoji: "🇹🇿", region: "Africa" },
  { name: "Thailand", iso: "th", emoji: "🇹🇭", region: "Asia" },
  { name: "Turkey", iso: "tr", emoji: "🇹🇷", region: "Asia" },
  { name: "UAE", iso: "ae", emoji: "🇦🇪", region: "Middle East" },
  { name: "USA", iso: "us", emoji: "🇺🇸", region: "North America" },
  { name: "Ukraine", iso: "ua", emoji: "🇺🇦", region: "Europe" },
  { name: "UK", iso: "gb", emoji: "🇬🇧", region: "Europe" },
  { name: "Vietnam", iso: "vn", emoji: "🇻🇳", region: "Asia" },
  { name: "Yemen", iso: "ye", emoji: "🇾🇪", region: "Middle East" },
];

export const REGIONS = [
  "All",
  "Asia",
  "Europe",
  "Middle East",
  "Africa",
  "North America",
  "South America",
  "Australia",
  "Central America",
  "Caribbean",
];
